.gitignore
package-lock.json
package.json
server.js

initialisation du repo github avec le language node js et le framework express

feat: init repo for back end with node js and framework express

---

src/db/db.ts
src/modules/orders/orders.controller.ts
src/modules/orders/orders.service.ts

fix: add field name and quantity

---

src/modules/orders/orders.controller.ts
src/modules/orders/orders.service.ts

add new route '/{restaurant_id}/orders/next/{id}'
#64 

orders/next/ API route

---

src/modules/details/DTO/detail.dto.ts
src/modules/food/DTO/food.dto.ts
src/modules/food_category/DTO/food_category.dto.ts
src/modules/ingredient/DTO/ingredient.dto.ts
src/modules/orders/DTO/food_ordered.dto.ts
src/modules/orders/DTO/orders.dto.ts
src/modules/restaurants/DTO/restaurants.dto.ts
src/modules/users/DTO/users.dto.ts

id field added into all DTO
#68 

add: id field into all DTO

---

src/modules/orders/DTO/orders.dto.ts
src/modules/orders/orders.controller.spec.ts
src/modules/orders/orders.controller.ts
src/modules/orders/orders.service.ts
src/modules/orders/pipe/status.pipe.ts

add new option ('servie') for param status into route 'api/:idRestaurant/orders'
Closes #82 

Route get Order servie

---

src/modules/food/food.controller.spec.ts
src/modules/food/food.controller.ts
src/modules/food/pipe/foodCategory.pipe.ts

new param into route 'api/:idRestaurant/food' for filter food to a category
Closes #88 

Add foodcategory params

---

docs/swagger.json
src/main.ts
src/modules/food/food.controller.spec.ts
src/modules/food/food.controller.ts
src/modules/food/food.service.ts
src/modules/food/pipe/useCase.pipe.ts

add a new param into '/api//{restaurant_id}/food/{id}' for choose a specific return for the POS
Closes #91 

Param 'useCase' into route get Food by ID

---

src/modules/orders/orders.controller.ts

add filter time with the param 'served'
Closes #93

add filter time with the param 'served'

---

src/modules/orders/orders.service.ts

filter status=ready and sort=time return only order ready and don't served
Closes #97 

Fix Param ready and sort by time

---

src/modules/orders/orders.controller.ts
src/modules/orders/orders.service.ts

Change the sort param to sort in ascending order
Launch the backend
Launch the KDS (CUISINE or PASSE)
The orders should now appear from the oldest to the newest
Closes #101 

Orders sorted in ascending orders

---

src/modules/orders/orders.service.ts

verify the size of the array before use every
call the route : /api/1/orders?sort=time&status=ready

Order not filtered correctly

---

docs/swagger.json
src/modules/users/DTO/users.dto.ts
src/modules/users/schemas/users.schema.ts
src/modules/users/users.controller.spec.ts

add stored first and last names in the user table
CRUD on /api/users
Closes #105 

feat: add stored first and last names

---

docs/swagger.json
src/modules/login/login.controller.spec.ts
src/modules/login/login.controller.ts
src/modules/login/login.service.ts

Return user's ID, first and last name with the access token on login
Login with existing credentials and check the response from the API
Closes #109 

109 return user id on login

---

docs/swagger.json
src/modules/orders/orders.controller.ts
src/modules/orders/orders.service.ts
src/modules/orders/pipe/channel.pipe.ts

add new route for get next number order
send this into postman : 'http://[::1]:3000/api/1/orders/number?channel=A emporter' or 'http://[::1]:3000/api/1/orders/number?channel=Sur place'
#112

Order number route

---

src/modules/details/details.service.ts
src/modules/food/food.service.ts
src/modules/food_category/food_category.service.ts

remove useless field update into service corresponding to old DTO
use route for update food, details or food_category and check if useless thing are create
#117 

Food/Detail/FoodCategory API route Update return junks

---

docs/swagger.json
src/modules/users/DTO/updatepassword.dto.ts
src/modules/users/users.controller.spec.ts
src/modules/users/users.controller.ts
src/modules/users/users.service.ts

Added route to change password
Log and try to change the password with the /user/{id}/password (See documentation for usage)
Closes #119 

feat: implement password update functionality with validation

---

docs/swagger.json
src/modules/orders/orders.controller.spec.ts
src/modules/orders/orders.controller.ts
src/modules/orders/orders.service.ts

change the return of the route post for create order to return id of the new order
create an order and check if the id is returned
#126 

Return ID order when is created

---

docs/swagger.json
src/modules/users/DTO/usersupdate.dto.ts
src/modules/users/users.controller.spec.ts
src/modules/users/users.controller.ts
src/modules/users/users.service.ts

We can use the PUT on user without the password row.
Edit a user using the PUT route. It should works without providing a password row.
Closes #128 

fix: update user without password

---

src/modules/orders/orders.controller.ts

delete the comparaison of price for check if it is the same food_ordered
get order with multiple food_ordered and check if the quantity is correctly
Closes #131 

Quantity for multiple food

---

docs/swagger.json
src/modules/orders/orders.controller.spec.ts
src/modules/orders/orders.controller.ts
src/modules/orders/orders.service.ts
src/modules/orders/pipe/tableID.pipe.ts

link table to order and can search by table id for find a specific order
link a order to a table and search it with the id of the table
Closes #113 

113 receive table id on the order route

---

src/modules/orders/orders.service.ts

the condition for link a table with a order when is create was change for juste check if is a number
Created an order with the idTable = 0 and check if the table is link to an order with the field OrderId
Closes #135 

ID table 0 was not detected

---

src/modules/orders/orders.service.ts

add timestamp into object table when a order is link to a table
add a new order with a link to a table and check if the row time was update into the object table
Closes #136 

Store TimeStamp to Table

---

src/modules/orders/orders.service.ts

remove field orderId when a payement was successfully past
made a payment for a new order
Closes #137 

Free table

---

docs/swagger.json
src/app.module.ts
src/modules/kpi/kpi.controller.spec.ts
src/modules/kpi/kpi.controller.ts
src/modules/kpi/kpi.module.ts
src/modules/kpi/kpi.service.ts
src/modules/kpi/pipe/date.pipe.ts
src/modules/orders/orders.service.ts

create a new module for the kpi and create a new route for calc average time to prepare one type of dish
use the route 'kpi/averageTimeDish/:food' and check if its work 
Closes #141 

Preparation time of a dish

---

src/modules/kpi/kpi.service.ts

replace the field time by timeReady into the return project for the call to the database
Call the following route 'averageTimeDish/:food' with any parameters
Closes #154 

BUG KPI average time for one dish

---

docs/swagger.json
src/modules/kpi/kpi.controller.spec.ts
src/modules/kpi/kpi.controller.ts
src/modules/kpi/kpi.service.ts
src/modules/kpi/pipe/breakdown.pipe.ts

add new route for get all average time for each food
call the route 'averageTimeAllDishes' and check is response
Closes #142 

Average time of all dishes

---

docs/swagger.json
src/modules/kpi/kpi.controller.spec.ts
src/modules/kpi/kpi.controller.ts
src/modules/kpi/kpi.service.ts
src/modules/kpi/pipe/channel.pipe.ts
src/modules/kpi/pipe/served.pipe.ts

add new route for get clientCount with different filter
Call the route 'clientsCount' and check is the data return is correct
Closes #144 

activeClientsCount

---

docs/swagger.json
src/modules/kpi/kpi.controller.spec.ts
src/modules/kpi/kpi.controller.ts
src/modules/kpi/kpi.service.ts

add new route for forecast the dish of one day
Use the route 'dishForecast' and check the data return
Closes #147 

dailyDishForecast

---

docs/swagger.json
src/modules/kpi/kpi.controller.spec.ts
src/modules/kpi/kpi.controller.ts
src/modules/kpi/kpi.service.ts

Add the route /kpi/averageBasket to compute the average basket value
Use the route /kpi/averageBasket and check what is returned
Closes #145 

145 average basket value

---

src/modules/food/food.service.ts

add new field 'suppPrice' for each ingredient containing the price of a ingredient
Call the route 'food/{id}?useCase=POS' and check the data return
Closes #170 

Return price of ingredient

---

src/modules/orders/DTO/food_ordered.dto.ts

just change the type from number to string
With the POS just create a order with a supp ingredient and check if its accept by the API
Closes #184 

Change the type of suppPrice into DTO
